import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { CssBaseline, ThemeProvider } from '@mui/material';
import { darkTheme } from '@/themes';
import { MainLayout } from '@/layouts';
import { ContextProvider } from '@/provider';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="jp">
			<ThemeProvider theme={darkTheme}>
				<body>
					<ContextProvider>
						<CssBaseline />
						<AppRouterCacheProvider>
							<MainLayout>{children}</MainLayout>
						</AppRouterCacheProvider>
					</ContextProvider>
				</body>
			</ThemeProvider>
		</html>
	);
}
